### ISSUE TITLE
Need SVG for logo

### ISSUE THREAD

**Issue by tw15egan** [IBM-Blue-Box-Help/help-documentation#157]
<img width="969" alt="screen shot 2016-06-16 at 11 48 05 am" src="https://cloud.githubusercontent.com/assets/11928039/16130005/e3941b3e-33cc-11e6-8f92-84ca96aa87db.png">

**Comment by LeslieLundquist** [comment]
@tw15egan for sure we need that .svg. I have put an email out to a wider list of people I know from Blue Box marketing who are now more plugged in to that stuff at IBM than I am. Cross your fingers!
